name: Frontend

on:
  pull_request:
    branches: ['develop'] # main 브랜치에 pull request될 때 동작 
  push:
    branches: ['develop'] # main 브랜치에 push될 때 동작

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd mz_v1_front
          npm install

      - name: Build SvelteKit app
        run: |
          cd mz_v1_front
          npm run build

  cd:
    runs-on: ubuntu-latest

    needs: ci

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER2_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER2_KEY}}
          port: ${{secrets.SERVER_PORT}}
          script: 'git clone https://github.com/Make-Zenerator/voice2face-frontend.git && git pull origin develop && ls && npm install && npm run build && pm2 start ./build/index.js'
